<?php

namespace Admin\CommonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsersRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
}
